### ISSUE TITLE
Hello, Could you please tell me how much time you spent training this model

### ISSUE THREAD

**Issue by junleiz** [BryanPlummer/cite#1]
Hello, I am trying your code and I found the training process is very low. I do not change anything of your code, and I used two GTX 1080 TI. The model may take 18 hours to train an epoch. I do not know whether there is anything wrong or it should be slow like this.

**Comment by junleiz** [comment]
Hello, while I am running your code, I found the GPU memory-usage is 100% but the Volatile GPU-Util is 0%. I wish to know whether you have met this problem. The whole training process is really slow

**Comment by BryanPlummer** [comment]
I would suspect you have fairly slow file i/o.  I would say on the Flickr30K Entities dataset it took a few days in the current implementation to train completely.  You could speed this up considerably by changing the batches to group samples by images, which would cut the time for each epoch down considerably, but in our experiments this reduced performance by about 1%.

**Comment by junleiz** [comment]
Hello, I rewrote your data_loader using the pytorch and read data in a multithreading way. It would significantly reduce training time.
Actually, I would like to try other proposals, such as those produced by RPN. I wish to produce visual features by myself. I wish to know the possibility that you could share the VGG16 model pretrained on Flickr30K and ReferIt.

Thank you very much for your time!

**Comment by BryanPlummer** [comment]
We never fine-tuned features for ReferIt in this paper.  Also, if you wish to use an RPN, then I would suggest you also use the feature representation produced by that model and not the features used here.  On a ResNet-101 model you should expect to get 95%+ recall  for 300 proposals for a RPN fine-tuned on the ReferIt and Flickr datasets, and a recall of around 70/51 for Flickr/Referit, respectively, as reported here:

https://arxiv.org/pdf/1811.07212.pdf

The code for the above paper will be released in the future.

**Comment by junleiz** [comment]
Thank you very much for your patient reply. It would be appreciated if you could release the finetune code^-^
