### ISSUE TITLE
Hello, Could you please tell me how you extract the visual features?

### ISSUE THREAD

**Issue by junleiz** [BryanPlummer/cite#3]
Hello, I extracted the visual features generated from the RPN using Faster RCNN. I wish to know whether you use the ROIPooling layer while extracting the features? Did you map the boxes to the Pool5 and pass them to a ROIPOOLING layer to get the feature (7*7) and then extract the fc7？ Since I did that but it does not work. The acc is only 33%. I thought the way I extracted features is wrong. Thank you.

**Comment by BryanPlummer** [comment]
An example of how we processed the data can be found here:

https://github.com/BryanPlummer/cite/tree/master/data_processing_example

It contains a link to another repo which can be used in conjunction with the provided script to extract the features as done in our paper.
