### ISSUE TITLE
Could you please upload the "fastrcnn_feat.prototxt" file？

### ISSUE THREAD

**Issue by junleiz** [BryanPlummer/cite#4]
Hello, I am very sorry to bother you. I wish to run your code to extract the visual features. But I can not find a place to download the fastrcnn_feat.prototxt" file. Could you please upload this file or Could you please tell me which layer (fc7 or fc7 relu) you used in your CITE paper?  Thank you very much

**Comment by BryanPlummer** [comment]
I doubt these choices would make much difference, but it would be fc7 plus relu.

**Comment by BryanPlummer** [comment]
The prototxt file is part of the precomputed data in the pl-clc repo if you would like to ensure you use the same files, however.
